### ISSUE TITLE
AndroidSDK ネットワークが不安定な時に getRegistrationIdInBackground で例外

### ISSUE THREAD

**Issue by yskfj** [NIFTYCloud-mbaas/UserCommunity#132]
Android ネットワークが不安定なときに例外を吐いているみたいです

クラッシュログを見ると
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
となっているので getRegistrationIdInBackground中に何かしらうまくいかないことがあり、スレッドでUI操作をしようとしている可能性が高いのでは？と疑っています

Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
       at android.os.Handler.(Handler.java:121)
       at android.os.AsyncTask$InternalHandler.(AsyncTask.java:607)
       at android.os.AsyncTask$InternalHandler.(AsyncTask.java:607)
       at android.os.AsyncTask.(AsyncTask.java:190)
       at com.nifty.cloud.mb.NCMBInstallation.getRegistrationIdInBackground()

**Comment by moongift** [comment]
@yskfj 
フレームワークの不具合の可能性がありますので調査中です。分かり次第information blogなどで報告します。もう少々お待ちください。
