### ISSUE TITLE
Installationに登録できません

### ISSUE THREAD

**Issue by papimomo** [NIFTYCloud-mbaas/UserCommunity#282]
AndroidでPushを実装しており、SDK Ver1.5.4でNCMBInstallationのgetRegistrationIdInBackgroundを
実行したところ、SERVICE_NOT_AVAILABLEとなってしまいます。
1週間程前に確認したときはInstallationに登録できていました。

以下は実際のログとなります。
W/System.err: com.nifty.cloud.mb.NCMBException: java.io.IOException: SERVICE_NOT_AVAILABLE
W/System.err:     at com.nifty.cloud.mb.NCMBInstallation$5.doInBackground(NCMBInstallation.java:296)
W/System.err:     at com.nifty.cloud.mb.NCMBInstallation$5.doInBackground(NCMBInstallation.java:1)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/System.err: Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
W/System.err:     at com.google.android.gms.gcm.GoogleCloudMessaging.zza(Unknown Source)
W/System.err:     at com.google.android.gms.gcm.GoogleCloudMessaging.register(Unknown Source)
W/System.err:     at com.nifty.cloud.mb.NCMBInstallation$5.doInBackground(NCMBInstallation.java:292)
W/System.err: ... 7 more

なお、SDKのVer2でも実装してみましたが、同様にSERVICE_NOT_AVAILABLEとなりました。

**Comment by papimomo** [comment]
Nexus7 Android4.4.4のみで発生していました。
Nexus7 Android6.0とNexus5 Android4.4.4では正常に登録できました。
