### ISSUE TITLE
ncmb_unity.2.0.0 でプッシュ通知実装でAndroid端末起動直後に強制終了

### ISSUE THREAD

**Issue by HitoshiMa** [NIFTYCloud-mbaas/UserCommunity#325]
ncmb_unity.2.0.0 でプッシュ通知実装するとAndroid用のビルドを行うと以下の様な警告が出ます
（とりあえずncmb登録とプッシュ通知の有効化以外は何もしていない状態です）

OBSOLETE - Providing Android resources in Assets/Plugins/Android/res is deprecated, please move your resources to an Android Library. See "Building Plugins for Android" section of the Manual.

.apk 自体は作成されるのですがandroid端末で動作させると起動直後に強制終了する端末と
正常動作をする端末があります。
以下の様なエラーが出ます。
-------------------------------------------------------------------------------------------------------
12-17 14:50:08.376: E/AndroidRuntime(23411): Device fingerprint: google/hammerhead/hammerhead:4.4.2/KOT49H/937116:user/release-keys
12-17 14:50:08.376: E/AndroidRuntime(23411): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.R$string
-------------------------------------------------------------------------------------------------------

・強制終了する端末では何回試みても強制終了します
・発生する端末の条件は未だわかりません（Nexus5で発生したのですが違うNexus5では正常動作しています）
・Unityは5.2.3f1を使用しています。

どなたか同様の現象が出ていませんでしょうか？その場合どのような対処をされましたでしょうか？

よろしくお願いいたします。

**Comment by HitoshiMa** [comment]
その後提供されたライブラリをAndroid Studio でAndroidライブラリ化して警告はでなくなったのですが
実行結果はAndroidライブラリ化する前と同じでした

E/AndroidRuntime(23411): Caused by: java.lang.NoClassDefFoundError: com.google.android.gms.R$string

についてどなたか分かりますでしょうか？

**Comment by HitoshiMa** [comment]
その後エラーを調べてみましたが

12-17 16:51:20.186: E/AndroidRuntime(614): 	at com.google.android.gms.common.GoogleApiAvailability.getErrorDialog(Unknown Source)
12-17 16:51:20.186: E/AndroidRuntime(614): 	at com.nifty.cloud.mb.ncmbgcmplugin.GCMInit.checkPlayServices(GCMInit.java:85)

とでています

GCMInit.checkPlayServices　で失敗してダイアログを出そうとして強制終了しているのでしょうか？

**Comment by HitoshiMa** [comment]
自分の端末で google play services が有効になっていなかったようで、有効にしたら
正常動作しました。
こちらは開発時は必ず有効である必要があるのでしょうか？
また開発環境以外でも google play services のチェックは行われるのでしょうか？

**Comment by AkihiroOta** [comment]
2.1.0でGoogle Play 開発者サービスのエラーが発生した場合にクラッシュする問題の対処がされているみたいです。

**Comment by moongift** [comment]
プッシュ通知絡みの場合、  google play services は有効になっている必要があるかと思います。

**Comment by HitoshiMa** [comment]
こちらの件ですが開発者サービスが無効だった場合ダイアログを出していた箇所を
コメントアウトしたソースをビルドすることで対処していました。
先日公開された2.0.1で対処されたのを確認しました。
よろしくお願いいたします。
※Labelの設定をpush通知にしたかったのですがわかりませんでした、すみません
