### ISSUE TITLE
【Android】fetchを呼ぶとcreateURLでNullPointerExceptionが起きてしまう

### ISSUE THREAD

**Issue by knsk17** [NIFTYCloud-mbaas/UserCommunity#380]
初めてお世話になります。よろしくお願い致します。
標題についてお伺いします。

Ver2.0.0を使用し、アプリアップデートに伴うDBのアップグレード処理を記述しているところです。
リリースビルドのアプリをadb install -rで、旧バージョンの入った実機にインストールしています。
ファイルストアからファイルを持ってきてDBにInsertする処理を行うところです。
SQLiteOpenHelper#onUpgrade内で、NCMBFile#fetch（fetchInBackgroundも同じ結果でした）を呼ぶと、
NullPointerExceptionが発生してしまいます。（以下エラー抜粋）

E/AndroidRuntime( 3143): Caused by: java.lang.NullPointerException
E/AndroidRuntime( 3143): at com.nifty.cloud.mb.core.NCMBFileService.createURL(NCMBFileService.java:406)

E/AndroidRuntime( 3143): 	at com.nifty.cloud.mb.core.NCMBFileService.fetchFile(NCMBFileService.java:272)

E/AndroidRuntime( 3143): 	at com.nifty.cloud.mb.core.NCMBFile.fetch(NCMBFile.java:262)

onUpgradeを呼ぶためのSQLiteOpenHelperは、
テスト的にMainActivityのonCreate内で以下のように呼んでいます。
`ScheduleOpenHelper helper = ScheduleOpenHelper.getInstance(this);`
`helper.getWritableDatabase();`

ソースコードを拝見したところ、該当箇所はcreateURLの
`StringBuilder url = new StringBuilder(mContext.baseUrl + mServicePath);
`
という箇所だったので、Contextの渡し方が悪いのか、adb installが原因なのか、
そもそもHelperで呼ぶのが良くないのかと思っているのですが、
なかなか解決の糸口がつかめません。他のActivity等で呼んでいるfetchは問題なく動作しております。
原因として考えられるところを教えていただきたいです。
よろしくお願い致します。

**Comment by knsk17** [comment]
大変失礼いたしました。
テスト的にhelperを呼び出す前に
`NCMB#initialize`をしていなかったことが原因だったようです…。
私の注意不足でお騒がせいたしました。
