### ISSUE TITLE
Androidでクラッシュする件について

### ISSUE THREAD

**Issue by kamiyoshiahra** [NIFTYCloud-mbaas/UserCommunity#437]
cocos2dx+eclipse+androidで
サイト通りの手順で
Push通知を組み込もうとすると

installation.getRegistrationIdInBackground("senderId", new DoneCallback() {
のNCMBException eで

com.nifty.cloud.mb.core.NCMBException: java.lang.IllegalStateException: 
The meta-data tag in your app's AndroidManifest.xml does not have the right value.
Expected 7327000 but found 0.  You must have the following declaration within the <application> element:
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

っと はき出されるので

<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />

を　追加したところ

installation.getRegistrationIdInBackground("senderId", new DoneCallback() {
の所で　NCMBException eも来ず
以下のようにクラッシュして落ちてしまいます。

04-25 22:47:53.482: E/AndroidRuntime(1992): FATAL EXCEPTION: AsyncTask #1
04-25 22:47:53.482: E/AndroidRuntime(1992): Process: net.example, PID: 1992
04-25 22:47:53.482: E/AndroidRuntime(1992): java.lang.RuntimeException: An error occured while executing doInBackground()
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.lang.Thread.run(Thread.java:818)
04-25 22:47:53.482: E/AndroidRuntime(1992): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at com.nifty.cloud.mb.core.NCMBInstallation.getDeviceTokenFromGCM(NCMBInstallation.java:457)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at com.nifty.cloud.mb.core.NCMBInstallation$1.doInBackground(NCMBInstallation.java:441)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at com.nifty.cloud.mb.core.NCMBInstallation$1.doInBackground(NCMBInstallation.java:437)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-25 22:47:53.482: E/AndroidRuntime(1992): 	... 4 more

解決策等ございましたらご教授頂けますと幸いです。

宜しくお願い致します。

**Comment by motty93** [comment]
同じ現象で詰まってました。
>Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;

ここですね
おそらくアプリケーション配下のモジュールを追加してないんじゃないでしょうか？
dependenciesに
`implementation 'com.google.android.gms:play-services-gcm:15.0.1' `
を追加で行けるはずです。

`com.google.android.gms:play-services-gcm`の最新はhttps://developers.google.com/android/guides/setup にあるのでバージョンを合わせてみてください。

よく見たら2016年の投稿でしたね。。。
