### ISSUE TITLE
contentAvailableが設定できない

### ISSUE THREAD

**Issue by essoecc** [NIFTYCloud-mbaas/UserCommunity#454]
contentAvailableを追加するとエラーが出ます。
falseに設定すると問題ないのですが、trueだとエラーになります。

Error: cannot POST https://mb.api.cloud.nifty.com:443/2013-09-01/push (400)

`

			var data = JSON.parse(document.form.json.value);

			var push = new ncmb.Push();
			push.set("immediateDeliveryFlag", true)
			    .set("target", ["ios", "android"])
				.set("deliveryExpirationTime", "1 day")
				.set("userSettingValue", data)
				.set("contentAvailable", true);

			push.send()
				.then(function(push) {

				})
				.catch(function(err) {
					alert(err);
				});

`

**Comment by moongift** [comment]
同じ条件で設定してみて作成できました。errをconsole.logするとエラーメッセージが出ると思うのですが、なんと出ているでしょう？

**Comment by essoecc** [comment]
確認ありがとうございます。
表示されるエラーは下記の通りでした。

Error: cannot POST https://mb.api.cloud.nifty.com:443/2013-09-01/push (400)
    at Response.toError (http://localhost/ncmb.min.js:34028:13)
    at Response.setStatusProperties (http://localhost/ncmb.min.js:34002:12)
    at new Response (http://localhost/ncmb.min.js:33896:8)
    at Request.<anonymous> (http://localhost/ncmb.min.js:34062:13)
    at Request.Emitter.emit (http://localhost/ncmb.min.js:9871:20)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost/ncmb.min.js:34448:10)

**Comment by nutcase** [comment]
私もダメですね。
contentAvailable":trueを付与すると400エラーになります。

なぜかfalseならエラーが出ないです。
