### ISSUE TITLE
[Android pusu通知] getRegistrationIdInBackgroundでRuntimeException

### ISSUE THREAD

**Issue by sbs-tanaka** [NIFTYCloud-mbaas/UserCommunity#531]
getRegistrationIdInBackground実行後にRuntimeExceptionが発生してしまいます。

> final NCMBInstallation installation = NCMBInstallation.getCurrentInstallation();
> installation.getRegistrationIdInBackground("281680343784", new DoneCallback() {....(省略

以下、エラーログです。

> E/AndroidRuntime(15473): FATAL EXCEPTION: AsyncTask #1
> E/AndroidRuntime(15473): Process: jp.co.hoge.sample, PID: 15473
> E/AndroidRuntime(15473): java.lang.RuntimeException: An error occurred while executing doInBackground()
> E/AndroidRuntime(15473): 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
> E/AndroidRuntime(15473): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
> E/AndroidRuntime(15473): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
> E/AndroidRuntime(15473): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
> E/AndroidRuntime(15473): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> E/AndroidRuntime(15473): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> E/AndroidRuntime(15473): 	at java.lang.Thread.run(Thread.java:818)
> E/AndroidRuntime(15473): Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
> E/AndroidRuntime(15473): 	at com.nifty.cloud.mb.core.NCMBInstallation.getDeviceTokenFromGCM(NCMBInstallation.java:457)
> E/AndroidRuntime(15473): 	at com.nifty.cloud.mb.core.NCMBInstallation$1.doInBackground(NCMBInstallation.java:441)
> E/AndroidRuntime(15473): 	at com.nifty.cloud.mb.core.NCMBInstallation$1.doInBackground(NCMBInstallation.java:437)
> E/AndroidRuntime(15473): 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
> E/AndroidRuntime(15473): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> E/AndroidRuntime(15473): 	... 3 more
> E/AndroidRuntime(15473): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.iid.InstanceID" on path: DexPathList[[zip file "/data/app/jp.picology.docomo.mahjong-2/base.apk"],nativeLibraryDirectories=[/data/app/jp.picology.docomo.mahjong-2/lib/arm64, /vendor/lib64, /system/lib64]]
> E/AndroidRuntime(15473): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
> E/AndroidRuntime(15473): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
> E/AndroidRuntime(15473): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
> E/AndroidRuntime(15473): 	... 8 more
> E/AndroidRuntime(15473): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.iid.InstanceID
> E/AndroidRuntime(15473): 		at java.lang.Class.classForName(Native Method)
> E/AndroidRuntime(15473): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
> E/AndroidRuntime(15473): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
> E/AndroidRuntime(15473): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
> E/AndroidRuntime(15473): 		... 9 more
> E/AndroidRuntime(15473): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

何が原因で発生しているのか分からず困っております。
発生原因等、アドバイス頂けますと助かります。

以上、よろしくお願いいたします。

**Comment by sbs-tanaka** [comment]
自己解決につき記載しておきます。

google-play-services_libをrev29に更新したのと
プロジェクトを作成し直しで解決しました。
原因はgoogle-play-services_libだと思います。

プロジェクトを一から作成し直しで
google-play-services_libが正しく読込されるようになったのかなと
推測しております。

ご参考になれば
