### ISSUE TITLE
[Android]getCurrentInstallation() でNullPointerException発生

### ISSUE THREAD

**Issue by yukiet0099** [NIFTYCloud-mbaas/UserCommunity#580]
以下のバージョン・端末にて、アプリケーションの起動時に強制終了する問題が発生しております。
(こちらでは再現しておりませんが、エンドユーザ様からの問い合わせで、クラッシュログをいただいております)
NCMB SDKモジュール内での問題のため、以下の部分の確認をいただけませんでしょうか
SDK改修 or ユーザ様への対処方法をご教授いただきたく思います

===============
NCMB SDK v2.2.3
docomo SO－02F 
Android 4.4.2
===============

Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.nifty.cloud.mb.core.NCMBInstallation.getCurrentInstallation(NCMBInstallation.java:381)
	at *****.Activity.onResume(*****Activity.java:201)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
	at android.app.Activity.performResume(Activity.java:5310)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2840)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
	at org.json.JSONTokener.nextValue(JSONTokener.java:94)
	at org.json.JSONObject.<init>(JSONObject.java:155)
	at org.json.JSONObject.<init>(JSONObject.java:172)
	at com.nifty.cloud.mb.core.NCMBLocalFile.readFile(NCMBLocalFile.java:52)
	at com.nifty.cloud.mb.core.NCMBInstallation.getCurrentInstallation(NCMBInstallation.java:374)

====(対象部分のソース)
L:200 if (((Application)getApplication()).isGooglePlayServicesAvailable()) {
L:201    final NCMBInstallation installation = NCMBInstallation.getCurrentInstallation();

**Comment by schibawing** [comment]
事象としては下記と同様ではないでしょうか。
[ローカルファイル読込時にNullPointerExceptionが発生することがある](https://github.com/NIFTYCloud-mbaas/ncmb_android/issues/78)

**Comment by moongift** [comment]
ニフティ側の正式回答が欲しい場合、Expertプランのテクニカルサポートを受ける方が良いかと思います。

http://mb.cloud.nifty.com/support.htm
