### ISSUE TITLE
リレーションを含むレコードを更新できない。

### ISSUE THREAD

**Issue by DaichiSaito** [NIFTYCloud-mbaas/UserCommunity#723]
javascript SDK ver 2.1.5使用

カラムにリレーションを含むレコードを更新しようとすると、下記エラーとなります。

````
TypeError: obj.save is not a function
    at /Users/・・省略・・/node_modules/ncmb/lib/request.js:56:16
    at Array.map (native)
    at presavePointerObjects (/Users/・・省略・・/node_modules/ncmb/lib/request.js:28:40)
    at NCMB.<anonymous> (/Users/・・省略・・/node_modules/ncmb/lib/request.js:138:9)
    at NCMB.module.exports [as request] (/Users/・・省略・・/node_modules/ncmb/lib/request.js:108:10)
    at DataStore.Data.update (/Users/・・省略・・/node_modules/ncmb/lib/datastore.js:118:21)
    at /Users/・・省略・・/sample.js:135:18
    at process._tickCallback (internal/process/next_tick.js:109:7)
````

具体的なコードです。
````
SampleClass.equalTo("objectId",req.params.objectId)
  .fetch()
  .then(function(result) {
    result.set("name","ポチ");
    return result.update();
  })
````
他クラスへのリレーションを持っているレコードをupdate()した場合→上記エラー
他クラスへのリレーションを持っていないレコードをupdate()した場合→正常に更新できる

リレーションを含む場合は何か特別な処理が必要なのでしょうか...?
よろしくお願いします。

**Comment by moongift** [comment]
こちら恐らく不具合だと思います。

https://github.com/NIFTYCloud-mbaas/ncmb_js/issues

にてIssue登録をお願いできますか？

**Comment by DaichiSaito** [comment]
Issueにあげました。
回答ありがとうございます。
