### ISSUE TITLE
android 7.0, mbaas SDK2.2.5で This device is not supported google-play-services-APK

### ISSUE THREAD

**Issue by realdev01** [NIFTYCloud-mbaas/UserCommunity#765]
android 7.0
nexus 6P

下記のエラーが発生していますが、何かバージョンの問題でしょうか？

08-23 10:56:33.308 7319-7319/? W/System.err: com.nifty.cloud.mb.core.NCMBException: java.lang.IllegalArgumentException: This device is not supported google-play-services-APK.
08-23 10:56:33.308 7319-7319/? W/System.err:     at com.nifty.cloud.mb.core.NCMBInstallation.getRegistrationIdInBackground(NCMBInstallation.java:431)
08-23 10:56:33.308 7319-7319/? W/System.err:     at com.donki.majica.utils.NCMBUtils.initNCMB(NCMBUtils.java:41)
08-23 10:56:33.308 7319-7319/? W/System.err:     at com.donki.majica.ui.MainActivity.onCreate(MainActivity.java:125)
08-23 10:56:33.308 7319-7319/? W/System.err:     at com.donki.majica.ui.MainActivity_.onCreate(MainActivity_.java:42)
08-23 10:56:33.308 7319-7319/? W/System.err:     at android.app.Activity.performCreate(Activity.java:6664)
08-23 10:56:33.308 7319-7319/? W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.os.Looper.loop(Looper.java:154)
08-23 10:56:33.309 7319-7319/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
08-23 10:56:33.309 7319-7319/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-23 10:56:33.309 7319-7319/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
08-23 10:56:33.309 7319-7319/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
08-23 10:56:33.309 7319-7319/? W/System.err: Caused by: java.lang.IllegalArgumentException: This device is not supported google-play-services-APK.
08-23 10:56:33.309 7319-7319/? W/System.err:     at com.nifty.cloud.mb.core.NCMBInstallation.checkPlayServices(NCMBInstallation.java:473)
08-23 10:56:33.309 7319-7319/? W/System.err:     at com.nifty.cloud.mb.core.NCMBInstallation.getRegistrationIdInBackground(NCMBInstallation.java:428)
08-23 10:56:33.309 7319-7319/? W/System.err: 	... 15 more
08-23 10:56:33.543 7319-7319/? I/GAv4: Google Analytics 11.0.10 is starting up. To enable debug logging on a device run:
                                         adb shell setprop log.tag.GAv4 DEBUG
                                         adb logcat -s GAv4

**Comment by goofmint** [comment]
Google Playが入っていない、というわけではないんですよね？

**Comment by realdev01** [comment]
2.3.0に変えると正常にできていますので google playは入って入ると思いますがどうでしょうか？
